"""REST endpoint: trigger a macro briefing from the frontend.

Returns one of two payload kinds:

- `briefing` — generated by Claude (paid). Only when CLAUDE_API_KEY is set.
- `snapshot` — the same markdown the LLM would have received as a user
  prompt. Free, no API call. The user can copy/paste this into an external
  Claude session (e.g. Claude Code's /dtb-brief) to get a briefing without
  spending Anthropic API credits.

The use-case layer already caches the LLM response by prompt-hash for 24h
(see `GenerateBriefingUseCase`), so repeated clicks within a day cost at most
one paid call.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Literal

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from api.broadcaster import broadcaster
from container import build_container
from settings import get_settings
from use_cases.generate_briefing import (
    SYSTEM_PROMPT_EN,
    SYSTEM_PROMPT_PT,
    format_tick_payload,
)

logger = logging.getLogger(__name__)


class BriefResponse(BaseModel):
    kind: Literal["briefing", "snapshot"]
    content: str  # markdown
    timestamp: datetime
    model: str | None = None  # populated when kind == "briefing"
    note: str | None = None  # short user-facing note (cost or instructions)


router = APIRouter(prefix="/api", tags=["brief"])


@router.post("/brief", response_model=BriefResponse)
async def generate_brief() -> BriefResponse:
    """Try to generate a Claude briefing. Fall back to the raw snapshot if
    the API key is not configured."""
    settings = get_settings()
    tick = broadcaster.latest
    if tick is None:
        raise HTTPException(status_code=503, detail="No tick yet; backend warming up")

    has_key = bool(settings.claude_api_key.get_secret_value().strip())

    # Free path: return the markdown that *would* have been sent to the LLM.
    if not has_key:
        system_prompt = SYSTEM_PROMPT_PT if settings.output_language == "pt" else SYSTEM_PROMPT_EN
        payload = format_tick_payload(tick)
        content = (
            "## Como usar este snapshot\n\n"
            "`CLAUDE_API_KEY` não está configurada. O backend devolveu apenas os "
            "dados que ele teria enviado ao Claude — você pode copiar tudo abaixo "
            "(usando o botão acima) e colar no seu Claude Code com `/dtb-brief` "
            "para gerar o briefing sem custo.\n\n"
            "---\n\n"
            "### System prompt (papel do Claude)\n\n"
            f"```\n{system_prompt}\n```\n\n"
            "### Dados de mercado\n\n"
            f"{payload}\n"
        )
        return BriefResponse(
            kind="snapshot",
            content=content,
            timestamp=tick.timestamp,
            note=(
                "Sem custo. Configure CLAUDE_API_KEY no .env para gerar o briefing "
                "diretamente aqui (≈ $0.10-0.20 por click, com cache de 24h)."
            ),
        )

    # Paid path: actually call the LLM through the container.
    container = await build_container(settings)
    try:
        output = await container.generate_briefing.execute(tick)
        return BriefResponse(
            kind="briefing",
            content=output.content,
            timestamp=output.created_at,
            model=output.model,
            note=(
                "Resposta do Claude. Cache de 24h por hash do payload — cliques "
                "subsequentes no mesmo dia não geram novo custo."
            ),
        )
    finally:
        await container.aclose()
