"""REST endpoint: latest cached tick."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException

from api.broadcaster import broadcaster
from core.models import DashboardTick

router = APIRouter(prefix="/api", tags=["tick"])


@router.get("/tick", response_model=DashboardTick)
async def get_tick() -> DashboardTick:
    """Return the most recent DashboardTick.

    Returns 503 until the first tick has been generated by the loop. The
    frontend should retry on this status — usually resolves within seconds
    after backend boot.
    """
    tick = broadcaster.latest
    if tick is None:
        raise HTTPException(status_code=503, detail="No tick yet; backend warming up")
    return tick
